---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /root/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - /root//homepage/icons:/app/public/icons # Icons Path
      - /root/homepage/images:/app/public/images # Images Path
    environment:
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_VAR_OPENWEATHER_API_KEY: $HOMEPAGE_VAR_OPENWEATHER_API_KEY
